/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihmMPT;

import metierClass.*;
import interBD.BDD;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mdeschamps
 */
public class IHMReservation extends javax.swing.JDialog {
    
    private Pattern patterNbrePersonne;
    private Matcher matcherNbrePersonne;

    /**
     * Creates new form IHMReservation
     */
    public static List<Adherent> adhe = new ArrayList<>(); 
    public static List<Representation> repres = new ArrayList<>();
    public static List<Reservation> resa = new ArrayList<>();
    
    public IHMReservation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        jT_NbrePersonnes.setText("1");
        jT_ChampsTotal.setText("0");
        
        BDD.lireBdd("ADHERENT");
        BDD.lireBdd("REPRESENTATION");
        //BDD.lireBdd("RESERVATION");
        
        for(int i = 0 ; i <adhe.size(); i++)
        {
            Adherent liste = (Adherent)adhe.get(i);
            ListAdherent.addItem(liste.getNomAdherent()+" "+ liste.getPrenomAdherent());
        }
        for(int i = 0 ; i <repres.size(); i++)
        {
            Representation liste = (Representation)repres.get(i);
            ListRepresentation.addItem(liste.getDateRepresentation()+" "+ liste.getNomSpectacle());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Adherent = new javax.swing.JLabel();
        jL_Representation = new javax.swing.JLabel();
        jL_Nbrepersonne = new javax.swing.JLabel();
        jL_personnes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ListAdherent = new javax.swing.JComboBox();
        ListRepresentation = new javax.swing.JComboBox();
        jT_NbrePersonnes = new javax.swing.JTextField();
        jT_ChampsTotal = new javax.swing.JTextField();
        jB_Valider = new javax.swing.JButton();
        jB_Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservation Spectacle");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jL_Adherent.setText("Adhérent :");

        jL_Representation.setText("Représentation :");

        jL_Nbrepersonne.setText("Nombre de personnes :");

        jL_personnes.setText("personne(s)");

        jLabel4.setText("Total :");

        ListAdherent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélection" }));

        ListRepresentation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélection" }));
        ListRepresentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListRepresentationActionPerformed(evt);
            }
        });

        jT_NbrePersonnes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jT_NbrePersonnesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_NbrePersonnesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jT_NbrePersonnesKeyTyped(evt);
            }
        });

        jT_ChampsTotal.setEnabled(false);

        jB_Valider.setText("VALIDER");
        jB_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ValiderActionPerformed(evt);
            }
        });

        jB_Quitter.setText("QUITTER");
        jB_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_QuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_Nbrepersonne)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jT_ChampsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_NbrePersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jL_personnes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_Adherent)
                                .addGap(29, 29, 29))
                            .addComponent(jL_Representation, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_Quitter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Adherent)
                    .addComponent(ListAdherent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_Representation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_Nbrepersonne)
                    .addComponent(jT_NbrePersonnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_personnes))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_ChampsTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Valider)
                    .addComponent(jB_Quitter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_QuitterActionPerformed
         int selectedOption = JOptionPane.showConfirmDialog(null,"Voulez-vous Quitter ce programme?", "INFORMATION",JOptionPane.YES_NO_OPTION);    
         if (selectedOption == JOptionPane.YES_OPTION)
         {
             System.exit(0);
         }
    }//GEN-LAST:event_jB_QuitterActionPerformed

    private void jB_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ValiderActionPerformed
        
       
        
        try{
            jL_Adherent.setForeground(Color.BLACK);
            jL_Representation.setForeground(Color.BLACK);
            jL_personnes.setForeground(Color.BLACK);
            jL_Nbrepersonne.setForeground(Color.BLACK);
                
            
            
            String Verification="Veuillez remplir correctement le(s) champ(s): "+"\n";
            
            
            if ("Sélection".equals(ListAdherent.getSelectedItem().toString())) {
                jL_Adherent.setForeground(Color.red);
                Verification+="--> Adhérent"+"\n";
            }
            if ("Sélection".equals(ListRepresentation.getSelectedItem().toString())) {
                jL_Representation.setForeground(Color.red);
                Verification+="--> Représentation"+"\n";
            }
            
            
            if( "Sélection".equals(ListAdherent.getSelectedItem().toString()) || 
                "Sélection".equals(ListRepresentation.getSelectedItem().toString()))
            {
            JOptionPane.showMessageDialog(null, Verification, "Attention", JOptionPane.ERROR_MESSAGE);    
            }else{
                BDD.ecrireBdd("RESERVATION");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Attention", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jB_ValiderActionPerformed

    private void ListRepresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListRepresentationActionPerformed
        try{
          int repreSelect = (ListRepresentation.getSelectedIndex()-1);
        int tarif = repres.get(repreSelect).getTarif();
        double result = tarif*Integer.parseInt(jT_NbrePersonnes.getText());
        jT_ChampsTotal.setText(Double.toString(result));
        }catch(NumberFormatException|ArrayIndexOutOfBoundsException nb){
          jT_ChampsTotal.setText("0");   
        }
        
    }//GEN-LAST:event_ListRepresentationActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int selectedOption = JOptionPane.showConfirmDialog(null,"Voulez-vous Quitter ce programme?", "INFORMATION",JOptionPane.YES_NO_OPTION);    
         if (selectedOption == JOptionPane.YES_OPTION)
         {
            System.exit(0);
         }
    }//GEN-LAST:event_formWindowClosing
    private void jT_NbrePersonnesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_NbrePersonnesKeyReleased
        try{
           CalculerPrixTotal(); 
        }catch(NumberFormatException|ArrayIndexOutOfBoundsException nb){
            jT_ChampsTotal.setText("0");
        }
    }//GEN-LAST:event_jT_NbrePersonnesKeyReleased

    private void jT_NbrePersonnesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_NbrePersonnesKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE))
        {
        evt.consume();
        }
    }//GEN-LAST:event_jT_NbrePersonnesKeyTyped

    private void jT_NbrePersonnesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_NbrePersonnesKeyPressed
        if(evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_V) 
        {
        evt.consume();
        }
    }//GEN-LAST:event_jT_NbrePersonnesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                javax.swing.UIManager.setLookAndFeel(
                        javax.swing.UIManager.getSystemLookAndFeelClassName());

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IHMReservation dialog = new IHMReservation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void CalculerPrixTotal(){
        
        int tarif = repres.get(ListRepresentation.getSelectedIndex()-1).getTarif(); 
        int prixTotal= tarif*Integer.parseInt(jT_NbrePersonnes.getText());
        jT_ChampsTotal.setText(Integer.toString(prixTotal));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ListAdherent;
    private javax.swing.JComboBox ListRepresentation;
    private javax.swing.JButton jB_Quitter;
    private javax.swing.JButton jB_Valider;
    private javax.swing.JLabel jL_Adherent;
    private javax.swing.JLabel jL_Nbrepersonne;
    private javax.swing.JLabel jL_Representation;
    private javax.swing.JLabel jL_personnes;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jT_ChampsTotal;
    private javax.swing.JTextField jT_NbrePersonnes;
    // End of variables declaration//GEN-END:variables
}
